#
# PLUGINS OPTIONS
#
offscreenreload           0
hiscore                   0
discord                   0
portname                  0
data                      1
cheat                     0
timecode                  0
gdbstub                   0
console                   0
dummy                     0
layout                    1
autofire                  0
timer                     0
vector                    0
cheatfind                 0
inputmacro                0
